# Generated by Django 5.1.7 on 2025-04-25 14:57

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('charity', 'UserProfile')
    
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

def reverse_user_profiles(apps, schema_editor):
    UserProfile = apps.get_model('charity', 'UserProfile')
    UserProfile.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('charity', '0002_remove_charitycase_deadline_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles, reverse_user_profiles),
    ]
